model = "gpt-5-codex"

# DeepWiki (remote SSE) -> bridge to stdio for Codex using mcp-proxy
[mcp_servers.deepwiki]
command = "uvx"
args = ["mcp-proxy", "https://mcp.deepwiki.com/sse"]

[mcp_servers.ix-design-mcp]
command = "/mnt/c/Users/hvksh/mcp-servers/venv312/Scripts/python.exe"
args = [
  "C:\\Users\\hvksh\\mcp-servers\\ix-design-mcp\\server.py",
]

startup_timeout_ms = 600_000

[mcp_servers.ix-design-mcp.env]
IX_DESIGN_MCP_ROOT = "/mnt/c/Users/hvksh/mcp-servers/ix-design-mcp"
PHREEQC_RUN_TIMEOUT_S = "600"
MCP_SIMULATION_TIMEOUT_S = "600"

[projects."/mnt/c/Users/hvksh/mcp-servers/ix-design-mcp"]
trust_level = "trusted"
